name: Release

on:
  push:
    branches:
      - main

jobs:
  release-action:
    runs-on: ubuntu-latest
    name: Release jira-git-issue action
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: TheRealWaldo/quick-release@v0.4.1
        with:
          token: ${{ secrets.AUTO_PAT }}
          replace-files: README.md
          git-user-email: 68967746+TRW-bot@users.noreply.github.com
          assignees: TheRealWaldo
